### ISSUE TITLE
Future plans and improvement

### ISSUE THREAD

**Issue by samayo** [shershen08/vuejs-sound-player#2]
I spent hours looking for audio players, but I didn't think someone made with  one with vuejs yet. 

Thanks for making this, I just would like to know if you will be adding features to it, basic features as loop, and if there is any way to find out when a track ends playing, such as trigger an event, or show list of loaded tracks in a template..

I would love to help, but I am still learning vue, hopefuly in the future I will contribute this library. 

Keep it up :+1:

**Comment by shershen08** [comment]
Hey, @samayo thanks for the positive feedback!

I actually didn't think of what else could be added. But thanks for raising those points:
- [ ] add loop button
- [ ] custom events (play/pause/finished)
- [ ] make some buttons customisable, so that you can select what to show (download, mute, loop)
- [ ] dark UI theme (CSS)
 
I'll try to add those soon then. If you wanna try with any those - feel free to fork a repo and submit a PR later!

About that:

> or show list of loaded tracks in a template..

I think it's a but outside of the scope of this plugin that only targets to wrap simple <audio> tag. Developer can implement list of loaded tracks in custom manner if needed with help of custom events, maybe.

**Comment by samayo** [comment]
Yeah, all those points would be nice. as for the loaded trucks, I meant something that just dumps the current list of tracks ex: passed to src, but this is trivial and can be shows with simple `v-for`. 


I would love to contribute, but I am not using ES6, npm, webpack, babel ... so, I can't do import, require ... sadly. It doesn't work on my VM, but I will try to contribute somehow.
